### PR TITLE
Create pl.ts

### PR DESCRIPTION
**Pull request by WerVa**
Add Polish lanugage

### CODE REVIEW

**Comment by guidopola** [comment]
Are you Jakub Werwiński? (Just to give credits in the app)

**Comment by WerVa** [comment]
Yes

Wysłane z iPhone'a

**Comment by moondeck** [comment]
Ah, you've beat me to it :smiley: 

Good job, but i would propose "Masa" instead of "Uziemienie", as "Uziemienie" implies the device has a ground reference. Well, actually they both do, so does "Ground", but "Ground" and "Masa" are also used as a reference to the "-" of a power supply, while "Uziemienie" never is.

**Comment by WerVa** [comment]
Ok, thanks for the advice! I'll correct my mistake

Wysłane z iPhone'a

**Comment by guidopola** [comment]
@moondeck what do you think about the changes?

**Comment by moondeck** [comment]
In line 264, there's no translation for "here", when linking to the github repo. Other than that it's fine.

**Comment by guidopola** [comment]
Thank you @WerVa & @moondeck

**Pull request merged**
