### PR TITLE
Added Bulgarian translation.

### PR DESCRIPTION
**Pull request by v00x**

### CODE REVIEW

**Comment by guidopola** [comment]
Hi! Thank you for the translation!
How did you edit the file? did you used Qt Linguist? I'm asking this because the strings are marked as "unfinished".
Could you mark them as finished?
With Qt Linguist you can mark them with the following button:
image

**Comment by AlekDuhov** [comment]
Hi!

I will make the corrections and send you new file.


С уважением,
Олег Агекян
067-474-74-74
On 08.03.2019 20:33:15, Georgi Angelov <notifications@github.com> wrote:
You can view, comment on, or merge this pull request online at:
  https://github.com/Phoneboard/phoneboard-i18n/pull/19 [https://github.com/Phoneboard/phoneboard-i18n/pull/19]
Commit Summary
* Added Bulgarian translation.
File Changes
* A bg.ts [https://github.com/Phoneboard/phoneboard-i18n/pull/19/files#diff-0] (408)
Patch Links:
* https://github.com/Phoneboard/phoneboard-i18n/pull/19.patch [https://github.com/Phoneboard/phoneboard-i18n/pull/19.patch]
* https://github.com/Phoneboard/phoneboard-i18n/pull/19.diff [https://github.com/Phoneboard/phoneboard-i18n/pull/19.diff]

**Comment by v00x** [comment]
Yeah i used Qt Linguist, but forgot to mark them as done. I edited the files, they are finished now.

**Comment by guidopola** [comment]
Thank you!

**Pull request merged**
